name: Build and deploy Node.js app to Azure Web App - ssreditor

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PORT: 8585
  NODE_ENV: "production"
  DB_PASS: ${{ secrets.DB_PASS }}
  SETGRID_API: ${{ secrets.setgrid_Api }}
  JWTSECRET: ${{ secrets.jwtSecret }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x]
        mongodb-version: ['6.0', '8.0.0']

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - name: Clear npm cache
      run: npm cache clean --force

    - name: Install dependencies
      run: npm install

    - name: Check for Mocha and Chai
      run: |
        npm list mocha
        npm list chai

    - name: Install Mocha globally
      run: npm install -g mocha

    - name: List installed packages
      run: npm list

    - run: npm test

    - name: Zip artifact for deployment
      run: zip release.zip ./* -r

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: node-app
        path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: node-app

    - name: Unzip artifact for deployment
      run: unzip release.zip

    - name: 'Deploy to Azure Web App'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v4
      with:
        app-name: 'ssreditor'
        slot-name: 'Production'
        package: .
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3CB5C450A3DE42099C6BD68E40320DE3 }}